server:
  max-http-request-header-size: 40KB  # Размер header для того, чтобы влезли все роли кейклоак в JWT токен
  forward-headers-strategy: FRAMEWORK  # Включаем проброс nginx заголовков для правильного определения URL в ответах
  http:
    encoding:
      charset: UTF-8
      enabled: true
  port: 8099

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  cache:
    cache-names:
      - rt-core
    caffeine:
      spec: maximumSize=1000, expireAfterAccess=180s
  web:
    resources:
      add-mappings: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
  config: classpath:logback-spring.xml

datasources:
  platform:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rtl?currentSchema=platform
    username: postgres
    password: postgres
    hikari:
      maxLifeTime: 600000
  orgstructure:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rtl?currentSchema=orgstructure
    username: postgres
    password: postgres
    hikari:
      maxLifeTime: 600000
  tasksetting:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rtl?currentSchema=tasksetting
    username: postgres
    password: postgres
    hikari:
      maxLifeTime: 600000

liquibase:
  platform:
    enabled: true
    change-log: classpath:db/changelog/platform/changelog.xml
    default-schema: platform
    liquibase-schema: platform
  orgstructure:
    enabled: true
    change-log: classpath:db/changelog/orgstructure/changelog.xml
    default-schema: orgstructure
    liquibase-schema: orgstructure
  tasksetting:
    enabled: true
    change-log: classpath:db/changelog/tasksetting/changelog.xml
    default-schema: tasksetting
    liquibase-schema: tasksetting