logging:
  level:
    ROOT: DEBUG

datasources:
  platform:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vkpht3?currentSchema=platform
    username: rostalent_user
    password: rostalent_pww_pg_2
    hikari:
      maxLifeTime: 600000
  orgstructure:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vkpht3?currentSchema=orgstructure
    username: rostalent_user
    password: rostalent_pww_pg_2
    hikari:
      maxLifeTime: 600000
  tasksetting:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vkpht3?currentSchema=tasksetting
    username: rostalent_user
    password: rostalent_pww_pg_2
    hikari:
      maxLifeTime: 600000

liquibase:
  platform:
    enabled: true
    change-log: classpath:db/changelog/platform/changelog.xml
    default-schema: platform
    liquibase-schema: platform
  orgstructure:
    enabled: true
    change-log: classpath:db/changelog/orgstructure/changelog.xml
    default-schema: orgstructure
    liquibase-schema: orgstructure
  tasksetting:
    enabled: true
    change-log: classpath:db/changelog/tasksetting/changelog.xml
    default-schema: tasksetting
    liquibase-schema: tasksetting